name: Test
on: push
jobs:
  typecheck:
    name: ts TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Type check
        run: npm run typecheck --if-present

  tests:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run Tests
        run: npm test
